### ISSUE TITLE
Blacklisted from Playground and Sidekick?

### ISSUE THREAD

**Issue by ryenchek** [NativeScript/playground-tutorials#33]
Hello, this I believe is going to be a bit of a strange post. I have been using Playground and Sidekick for a few weeks now and am suddenly unable to access either of them.  I can browse around the Internet fine, however, 

The Playground link: 
https://play.nativescript.org/?template=play-ng&tutorial=getting-started-ng&utm_medium=website&utm_campaign=useownrealestate&utm_source=nativescriptdotcom&utm_content=topnavgreenbutton

OR 

the NativeScript Docs link:
https://docs.nativescript.org/

Are unaccessable.  I am getting an error from Chrome (Version 70.0.3538.110 (Official Build) (64-bit): 

"This site can’t be reached docs.nativescript.org’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN"

OR

"This site can’t be reached play.nativescript.org’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN"

If I try to start Sidekick, it just gets stuck on the startup logo.

I have been using both Sidekick and Visual Studio Code to create a prototype mobile app but have not had any success with accessing my android phone via usb for debugging nor is the phone emulator from Android Studio very stable.  I have been using Playground off the NativeScript.org site to preview then download or copy the code locally to do cloud builds from Sidekick.  I have been doing this for about 3 weeks, now suddenly I can't access both.  I have a feeling I've been blacklisted.  Is there anyone who can help me out?  Can I request to the NativeScript folks to Unblacklist me if that is the case? Is there anyway to get a hold of the nativescript.org admins? Any help would be appreciated. Thank you.

**Comment by ryenchek** [comment]
Ok, I'm everything working now Sidekick and Playground now accessible.  However, I still don't know what the problem was.  Whether I got blacklisted by nativescript.org admins for 24hours or something regarding our own SOPHOS Endpoint software.  It would be nice to know what caused this anomaly.  Does anyone have any ideas?

**Comment by NickIliev** [comment]
@ryenchek glad to hear that you now have access - just as a note: we are not blacklisting anyone from the play.nativescript.org. It is more likely that you were probably experiencing some kind of connectivity issues or local ISP routing issues like DNS problems. If this do happens again contact your ISP to verify that their services are running and they can access play.nativescript.org and try the solutions [here](https://errorcodespro.com/error-code-dns_probe_finished_nxdomain/)

**Comment by ryenchek** [comment]
NickIliev..
Ok great, good to know and thank you for your response!!
